"""empty message

Revision ID: 542c81df5f93
Revises: 96d9b9455389
Create Date: 2020-08-29 11:32:38.484569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542c81df5f93'
down_revision = '96d9b9455389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'fid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    # ### end Alembic commands ###
